books_index:
    path:     /
    defaults: { _controller: "BookBundle:Book:index" }
    methods:  GET

books_show:
    path:     /{id}
    defaults: { _controller: "BookBundle:Book:show" }
    methods:  GET

books_new:
    path:     /
    defaults: { _controller: "BookBundle:Book:new" }
    methods:  POST

books_edit:
    path:     /{id}
    defaults: { _controller: "BookBundle:Book:edit" }
    methods:  PUT

books_delete:
    path:     /{id}
    defaults: { _controller: "BookBundle:Book:delete" }
    methods:  DELETE
